version: '3.8'

services:
  web:
    build: ./app
    # Run unit tests and start the server
    command: sh -c "python manage.py test && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=foo
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - SQL_ENGINE=django.db.backends.mysql
      - SQL_DATABASE=dev_test
      - SQL_USER=npcxdevadmin
      - SQL_PASSWORD=Uf_-e!.3FDhu
      - SQL_HOST=dev-npcx-usage.cazgawcwujhc.us-east-1.rds.amazonaws.com
      - SQL_PORT=3306    

#     depends_on:
#       - db
#   db:
#     image: postgres:13.0-alpine
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     environment:
#       - POSTGRES_USER=hello_django
#       - POSTGRES_PASSWORD=hello_django
#       - POSTGRES_DB=hello_django_dev

# volumes:
#   postgres_data:

